--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/creeperplayer20/C20s-TimeUI
build-by-default: true
branches:
- main
projects:
  C20s-TimeUI:
    path: ""
libs:
    - src: jojoe77777/FormAPI/libFormAPI
      version: ^1.3
...
